JobInterviewQuiz/JobInterviewQuiz/Controllers/AdminController.cs
using System.Web.Mvc;
using JobInterviewQuiz.Infrastructure;
using JobInterviewQuiz.Infrastructure.FilterAttribute;

namespace JobInterviewQuiz.Controllers
{
    public class AdminController : BaseController
    {
        [HttpGet]
        [ValidateQuizUser]
        public ActionResult StartPageAdmin()
        {
            if (!this.QuizUser.IsAdmin)
                RedirectToLogInPage();
            return View();
        }
    }
}

JobInterviewQuiz/JobInterviewQuiz/Controllers/TechnologyAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using JobInterviewQuiz.Dal.Sql;
using JobInterviewQuiz.Infrastructure;
using JobInterviewQuiz.Infrastructure.FilterAttribute;
using JobInterviewQuiz.Model.Dtos;
using JobInterviewQuiz.Model.ViewModels;

namespace JobInterviewQuiz.Controllers
{
    public class TechnologyAdminController : BaseController
    {
        TechnologyQuestionDal _technologyDal = new TechnologyQuestionDal();
        // GET: TechnologyAdmin
        [ValidateQuizUser]
        public ActionResult TechnologyCrud(TecnologyAdminViewModel model)
        {
            model.TechnologyQuestionAdminList = new List<TechnologyQuestion>();
            model.TechnologyQuestionAdminList = _technologyDal.GetAllTechnologyQuestions();
            model.TechnologyText = "";
            return View(model);
        }

        [HttpPost]
        public ActionResult AddTecnology(TecnologyAdminViewModel model)
        {
            model.TechnologyQuestionAdminList = _technologyDal.GetAllTechnologyQuestions();
            if (model.TechnologyQuestionAdminList.Any(p => string.Equals(p.TechnologyQuestionText, model.TechnologyAdminText, StringComparison.OrdinalIgnoreCase)) == false)
            {
                _technologyDal.AddTechnologyQuestion(model.TechnologyAdminText);
                return RedirectToAction("TechnologyCrud");
            }
            ModelState.AddModelError("TechnologyText", "This technology exist!");
            return View("TechnologyCrud", model);
        }

        [HttpPost]
        public ActionResult UpdateTecnology(TecnologyAdminViewModel model)
        {
            var technologyId = _technologyDal.GetAllTechnologyQuestions().Where(p => p.TechnologyQuestionText == model.TechnologyText).FirstOrDefault().Id;
            _technologyDal.UpdateTechnologyQuestionById(technologyId, model.TechnologyAdminText);
            return RedirectToAction("TechnologyCrud");
        }

        [HttpPost]
        public ActionResult DeleteTecnology(TecnologyAdminViewModel model)
        {
            var technologyId = _technologyDal.GetAllTechnologyQuestions().Where(p => p.TechnologyQuestionText == model.TechnologyText).FirstOrDefault().Id;
            _technologyDal.DeleteTechnologyQuestionById(technologyId);
            return RedirectToAction("TechnologyCrud");
        }

    }
}

JobInterviewQuiz/JobInterviewQuiz/Controllers/TestController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using JobInterviewQuiz.Helper;
using JobInterviewQuiz.Infrastructure;
using JobInterviewQuiz.Infrastructure.FilterAttribute;
using JobInterviewQuiz.Model.Dtos;
using JobInterviewQuiz.Model.ViewModels;
using JobInterViewQuiz.Dal;

namespace JobInterviewQuiz.Controllers
{
    public class TestController : BaseController
    {
        ITestTypeDal _testTypeDal;
        IQuestionDal _questionDal;
        ITechnologyQuestionDal _technologyQuestionDal;
        ITestsDal _testsDal;
        ITestQuestionsDal _testQuestionsDal;

        public TestController() : this(DalFactory.TestTypeDal(), DalFactory.QuestionDal(), DalFactory.TechnologyQuestionDal(), DalFactory.TestsDal(), DalFactory.TestQuestionsDal())
        {

        }

        public TestController(ITestTypeDal testTypeDal, IQuestionDal questionDal, ITechnologyQuestionDal technologyQuestionDal, ITestsDal testsDal, ITestQuestionsDal testQuestionsDal)
        {
            _testTypeDal = testTypeDal;
            _questionDal = questionDal;
            _technologyQuestionDal = technologyQuestionDal;
            _testsDal = testsDal;
            _testQuestionsDal = testQuestionsDal;
        }

        // GET: Test
        [ValidateQuizUser]
        public ActionResult Index()
        {

            TestViewModel model = new TestViewModel();

            model = FillData(model);


            TestViewModel.ErrorMessage = "";
            TestViewModel.SuccessMessage = "";


            return View(model);
        }



        [HttpPost]
        public ActionResult AddTest(TestViewModel model)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < model.TechQuestionNumber.Count; i++)
                    if (model.TechQuestionNumber[i] > _questionDal.GetAllQuestionsByLevelAndTechnology(model.TestLevel, _technologyQuestionDal.GetTechnologyQuestionByName(model.TechnologyQuestionsList[i]).Id).Count)
                    {
                        model = FillData(model);
                        TestViewModel.ErrorMessage = "There aren't enough questions available, please check Available Questions and try again ! ";
                        TestViewModel.SuccessMessage = "";
                        return View("Index", model);
                    }

                TestViewModel.ErrorMessage = "";
                TestViewModel.SuccessMessage = "Test saved to database !";


                var testTypeId = _testTypeDal.GetTestTypeByType(model.TestType).Id;
                var numberOfQuestions = model.TechQuestionNumber.Sum();

                _testsDal.AddTest(testTypeId, model.TestName, model.TestLevel, numberOfQuestions);

                var testId = _testsDal.GetAllTests().Where(r => r.TestTypeId == testTypeId && r.Name == model.TestName && r.LevelTest == model.TestLevel && r.NumberOfQuestions == numberOfQuestions).ToList()[0].Id;


                for (int i = 0; i < model.TechQuestionNumber.Count; i++)
                {
                    if (model.TechQuestionNumber[i] == 0)
                        continue;

                    var questionList = _questionDal.GetRandomQuestionsByLevelAndTechnology(model.TechQuestionNumber[i], model.TestLevel, _technologyQuestionDal.GetTechnologyQuestionByName(model.TechnologyQuestionsList[i]).Id);
                    foreach (var question in questionList)
                    {
                        _testQuestionsDal.AddTestQuestion(testId, question.Id);
                    }

                }




                model = FillData(model);



                return View("Index", model);
            }

            TestViewModel.ErrorMessage = "The Test Name field is required !";
            TestViewModel.SuccessMessage = "";

            model = FillData(model);

            return View("Index", model);
        }



        public TestViewModel FillData(TestViewModel model)
        {
            List<TestCustom> testList = new List<TestCustom>();

            foreach (var test in _testsDal.GetAllTests())
            {
                testList.Add(new TestCustom
                {
                    Id = test.Id,
                    TestTypeId = (int)test.TestTypeId,
                    Name = test.Name,
                    LevelTest = test.LevelTest,
                    NumberOfQuestions = test.NumberOfQuestions,
                    TestTypeString = _testTypeDal.GetTestTypeById((int)test.TestTypeId).Type,
                    TechValuesList = new List<int>()

                });
            }



            foreach (var test in testList)
            {

                var questionList = new List<Question>();

                foreach (var question in _testQuestionsDal.GetQuestionsIdsByTestId(test.Id))
                {
                    questionList.Add(_questionDal.GetQuestionById(question));
                }

                foreach (var tech in _technologyQuestionDal.GetAllTechnologyQuestions())
                {
                    //test.TechValuesList.Add(_testQuestionsDal.get _questionDal.GetAllQuestionsByLevelAndTechnology(test.LevelTest,tech.Id).Count);
                    test.TechValuesList.Add(questionList.Where(r => r.LevelQuestion == test.LevelTest && r.QuestionTechnologyID == tech.Id).Count());
                }
            }

            model = new TestViewModel
            {
                TestTypeList = _testTypeDal.GetAllTestType(),
                TestLevelList = _questionDal.GetAllQuestions().Select(r => r.LevelQuestion).Distinct().ToList(),
                TechnologyQuestionsList = _technologyQuestionDal.GetAllTechnologyQuestions().Select(r => r.TechnologyQuestionText).ToList(),
                TestList = testList


            };


            var rows = model.TechnologyQuestionsList.Count;
            var columns = model.TestLevelList.Count;

            model.QuestionGrid = new int[rows, columns];


            for (int i = 0; i < rows; i++)
                for (int j = 0; j < columns; j++)
                {
                    model.QuestionGrid[i, j] = _questionDal.GetAllQuestionsByLevelAndTechnology(model.TestLevelList[j], _technologyQuestionDal.GetTechnologyQuestionByName(model.TechnologyQuestionsList[i]).Id).Count;
                }


            return model;
        }

        [HttpPost]
        public void DeleteTest(int id)
        {
            _testsDal.DeleteTestById(id);
        }

    }
}

JobInterviewQuiz/JobInterviewQuiz/Views/Shared/MainLayout.cshtml
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*<link href="~/Content/bootstrap-cerulean.css" rel="stylesheet" />*@

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .navbar-nav {
            display: table;
            width: 100%;
            margin: 0;
        }

            .navbar-nav > li {
                float: none;
                display: table-cell;
                text-align: center;
            }

        .navbar navbar-inverse {
            background-color: #229922;
            color: #ffffff;
            border-radius: 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse">

            <div class="collapse navbar-collapse" id="navigation-elements">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="@Url.Action("StartPageAdmin", "Admin")"> Home </a>
                    </li>
                    <li>
                        <a href="@Url.Action("UserAdmin", "AdminUser")"> User </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home")"> Question </a>
                    </li>
                    <li>
                        <a href="@Url.Action("TechnologyCrud", "TechnologyAdmin")"> Category </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Test")"> Test </a>
                    </li>
                    <li>
                        <a href="@Url.Action("RedirectToLogInPage", "Base")"> Log out </a>
                    </li>
                </ul>
            </div>

        </nav>

    </div>

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

JobInterviewQuiz/JobInterviewQuiz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <title>@ViewBag.Title - My ASP.NET Application</title>

</head>
<body>
    <div class="imageLogo">
        <img src="/Images/logo.png">
    </div>
    <div class="container">
        <div class="row">
            @RenderBody()
            <hr />
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>